[build]
builder = "nixpacks"
baseDirectory = "."
dockerfile = "./Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 