[build]
builder = "nixpacks"
baseDirectory = "."
buildCommand = "dotnet restore backend.sln && dotnet publish backend.sln -c Release -o out"

[deploy]
startCommand = "dotnet out/backend.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 